-- Generated by tools/blender/build_guns.py. Do not edit by hand.
-- All vectors are in game space (studs): +X right, +Y up, -Z forward (barrel), origin = pistol-grip centre.
return {
	Guns = {
		M4 = {
			Length = 4.445,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.022, 0.368, -1.070), Size = Vector3.new(0.306, 0.625, 2.820), Triangles = 4664 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.189, 0.623), Size = Vector3.new(0.170, 0.991, 1.624), Triangles = 1674 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.020, 0.522, -0.825), Size = Vector3.new(0.302, 0.715, 4.369), Triangles = 2262 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.062, -0.758), Size = Vector3.new(0.158, 1.004, 0.485), Triangles = 544 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.490, -1.330), Size = Vector3.new(0.264, 0.284, 0.120), Triangles = 92 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.500, -3.010),
				Aim = Vector3.new(0.000, 0.830, 0.730),
				LeftHand = Vector3.new(0.000, 0.355, -1.750),
				Optic = Vector3.new(0.000, 0.680, -0.350),
				Underbarrel = Vector3.new(0.000, 0.355, -1.800),
				MuzzleMount = Vector3.new(0.000, 0.500, -2.880),
				Side = Vector3.new(0.125, 0.490, -2.000),
				MagWell = Vector3.new(0.000, 0.440, -0.695),
			},
		},
		MP5 = {
			Length = 4.180,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.405, -0.245), Size = Vector3.new(0.200, 0.450, 1.590), Triangles = 526 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.149, -0.030), Size = Vector3.new(0.268, 0.923, 3.260), Triangles = 1996 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.063, 0.461, -0.992), Size = Vector3.new(0.336, 0.675, 3.175), Triangles = 2592 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, -0.121, -0.761), Size = Vector3.new(0.120, 0.902, 0.442), Triangles = 460 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.411, -1.550), Size = Vector3.new(0.278, 0.159, 0.100), Triangles = 124 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.470, -2.580),
				Aim = Vector3.new(0.000, 0.750, 0.910),
				LeftHand = Vector3.new(0.000, 0.335, -1.330),
				Optic = Vector3.new(0.000, 0.685, -0.150),
				MagWell = Vector3.new(0.000, 0.330, -0.650),
			},
		},
		SR25 = {
			Length = 5.340,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.022, 0.368, -1.355), Size = Vector3.new(0.316, 0.625, 3.390), Triangles = 6030 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.241, 0.730), Size = Vector3.new(0.180, 1.095, 1.839), Triangles = 1278 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.020, 0.425, -1.120), Size = Vector3.new(0.312, 0.910, 5.139), Triangles = 2564 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, 0.122, -0.748), Size = Vector3.new(0.164, 0.663, 0.474), Triangles = 308 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.490, -1.460), Size = Vector3.new(0.274, 0.294, 0.120), Triangles = 92 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.500, -3.700),
				Aim = Vector3.new(0.000, 0.830, 0.730),
				LeftHand = Vector3.new(0.000, 0.350, -1.900),
				Optic = Vector3.new(0.000, 0.680, -0.400),
				Underbarrel = Vector3.new(0.000, 0.350, -2.200),
				MuzzleMount = Vector3.new(0.000, 0.500, -3.500),
				Side = Vector3.new(0.130, 0.490, -2.400),
				MagWell = Vector3.new(0.000, 0.440, -0.720),
			},
		},
		VSR = {
			Length = 5.870,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.106, -0.285), Size = Vector3.new(0.160, 0.787, 4.070), Triangles = 1190 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.160, 1.777), Size = Vector3.new(0.170, 0.680, 0.065), Triangles = 108 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.221, -1.288), Size = Vector3.new(0.174, 0.789, 5.544), Triangles = 2940 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, 0.264, -0.600), Size = Vector3.new(0.120, 0.193, 0.280), Triangles = 88 },
				{ Name = "Bolt", Role = "Metal", Center = Vector3.new(0.117, 0.424, 0.060), Size = Vector3.new(0.362, 0.251, 1.040), Triangles = 424 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.310, -1.680), Size = Vector3.new(0.168, 0.240, 0.120), Triangles = 156 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.480, -4.070),
				Aim = Vector3.new(0.000, 0.680, 0.910),
				LeftHand = Vector3.new(0.000, 0.230, -1.550),
				Optic = Vector3.new(0.000, 0.615, -0.250),
				Underbarrel = Vector3.new(0.000, 0.255, -2.000),
				MagWell = Vector3.new(0.000, 0.360, -0.600),
			},
		},
		M870 = {
			Length = 5.040,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.078, -0.740), Size = Vector3.new(0.210, 0.705, 1.180), Triangles = 1222 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, -0.075, 1.497), Size = Vector3.new(0.170, 0.730, 0.085), Triangles = 108 },
				{ Name = "Wood", Role = "Wood", Center = Vector3.new(0.000, -0.052, 0.650), Size = Vector3.new(0.160, 0.756, 1.620), Triangles = 316 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.055, -1.860), Size = Vector3.new(0.200, 0.560, 3.279), Triangles = 940 },
				{ Name = "Pump", Role = "Wood", Center = Vector3.new(0.000, 0.145, -1.880), Size = Vector3.new(0.184, 0.232, 0.900), Triangles = 1720 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.145, -1.398), Size = Vector3.new(0.188, 0.236, 0.055), Triangles = 80 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.250, -3.500),
				Aim = Vector3.new(0.000, 0.470, 0.450),
				LeftHand = Vector3.new(0.000, 0.035, -1.880),
				Optic = Vector3.new(0.000, 0.430, -0.750),
				MagWell = Vector3.new(0.000, -0.060, -1.020),
			},
		},
		AK74 = {
			Length = 5.000,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.477, -0.251), Size = Vector3.new(0.200, 0.355, 1.538), Triangles = 304 },
				{ Name = "Wood", Role = "Wood", Center = Vector3.new(0.000, 0.215, -0.120), Size = Vector3.new(0.200, 0.992, 3.480), Triangles = 1424 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.065, 0.320, -0.820), Size = Vector3.new(0.370, 0.800, 5.000), Triangles = 2126 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.187, -0.766), Size = Vector3.new(0.126, 1.034, 0.578), Triangles = 548 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.418, -1.620), Size = Vector3.new(0.212, 0.255, 0.120), Triangles = 156 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.480, -3.330),
				Aim = Vector3.new(0.000, 0.720, -0.600),
				LeftHand = Vector3.new(0.000, 0.310, -1.500),
				Optic = Vector3.new(0.000, 0.690, -0.200),
				MuzzleMount = Vector3.new(0.000, 0.480, -3.020),
				MagWell = Vector3.new(0.000, 0.330, -0.640),
			},
		},
		VECTOR = {
			Length = 3.065,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.310, -0.485), Size = Vector3.new(0.240, 0.740, 2.010), Triangles = 2478 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.178, 0.646), Size = Vector3.new(0.170, 0.974, 1.617), Triangles = 1452 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.030, 0.492, -0.115), Size = Vector3.new(0.260, 0.656, 2.989), Triangles = 1248 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.175, -0.630), Size = Vector3.new(0.134, 0.890, 0.224), Triangles = 176 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.128, 0.027), Size = Vector3.new(0.172, 0.123, 0.215), Triangles = 60 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.360, -1.610),
				Aim = Vector3.new(0.000, 0.800, 0.850),
				LeftHand = Vector3.new(0.000, 0.050, -0.920),
				Optic = Vector3.new(0.000, 0.680, -0.300),
				Underbarrel = Vector3.new(0.000, 0.205, -1.340),
				MuzzleMount = Vector3.new(0.000, 0.360, -1.520),
				Side = Vector3.new(0.125, 0.360, -1.340),
				MagWell = Vector3.new(0.000, 0.270, -0.630),
			},
		},
		MP7 = {
			Length = 2.520,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.170, -0.319), Size = Vector3.new(0.270, 0.999, 1.518), Triangles = 2930 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.190, 0.185), Size = Vector3.new(0.180, 0.820, 2.030), Triangles = 436 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.457, -0.100), Size = Vector3.new(0.230, 0.626, 2.440), Triangles = 792 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.117, 0.056), Size = Vector3.new(0.114, 0.745, 0.332), Triangles = 176 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.050, -0.745), Size = Vector3.new(0.112, 0.080, 0.200), Triangles = 44 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.420, -1.320),
				Aim = Vector3.new(0.000, 0.780, 0.860),
				LeftHand = Vector3.new(0.000, 0.000, -0.745),
				Optic = Vector3.new(0.000, 0.670, -0.250),
				MuzzleMount = Vector3.new(0.000, 0.420, -1.140),
				Side = Vector3.new(0.135, 0.420, -0.750),
				MagWell = Vector3.new(0.000, 0.240, -0.045),
			},
		},
		P90 = {
			Length = 2.660,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.317, -0.048), Size = Vector3.new(0.320, 1.075, 2.416), Triangles = 2228 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.230, 1.135), Size = Vector3.new(0.240, 0.660, 0.130), Triangles = 144 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.140, -0.810), Size = Vector3.new(0.340, 0.719, 1.300), Triangles = 532 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, 0.655, 0.200), Size = Vector3.new(0.240, 0.130, 1.560), Triangles = 108 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.134, -0.530), Size = Vector3.new(0.274, 0.168, 0.180), Triangles = 44 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.460, -1.460),
				Aim = Vector3.new(0.000, 0.920, 0.350),
				LeftHand = Vector3.new(0.000, -0.140, -0.560),
				Optic = Vector3.new(0.000, 0.855, -0.550),
				MuzzleMount = Vector3.new(0.000, 0.460, -1.320),
				Side = Vector3.new(0.165, 0.460, -0.900),
				MagWell = Vector3.new(0.000, 0.720, 0.200),
			},
		},
		M249 = {
			Length = 5.400,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.045, 0.465, -0.685), Size = Vector3.new(0.350, 0.780, 2.330), Triangles = 1652 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.177, 0.000), Size = Vector3.new(0.240, 0.966, 3.800), Triangles = 1626 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.233, -1.477), Size = Vector3.new(0.530, 1.391, 4.045), Triangles = 2154 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(-0.090, 0.116, -0.520), Size = Vector3.new(0.319, 0.933, 0.640), Triangles = 824 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.415, -1.610), Size = Vector3.new(0.252, 0.230, 0.120), Triangles = 156 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.550, -3.510),
				Aim = Vector3.new(0.000, 0.900, 0.620),
				LeftHand = Vector3.new(0.000, 0.310, -1.500),
				Optic = Vector3.new(0.000, 0.855, -0.450),
				Underbarrel = Vector3.new(0.000, 0.310, -1.550),
				MuzzleMount = Vector3.new(0.000, 0.550, -3.330),
				Side = Vector3.new(0.150, 0.450, -1.520),
				MagWell = Vector3.new(-0.080, 0.300, -0.520),
			},
		},
		G17 = {
			Length = 1.411,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.016, -0.486), Size = Vector3.new(0.170, 0.660, 1.387), Triangles = 1357 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.003, 0.297, -0.690), Size = Vector3.new(0.173, 0.366, 0.990), Triangles = 516 },
				{ Name = "Mag", Role = "Primary", Center = Vector3.new(0.000, -0.075, 0.019), Size = Vector3.new(0.144, 0.665, 0.385), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(0.000, 0.415, -0.550), Size = Vector3.new(0.160, 0.250, 1.300), Triangles = 630 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.194, 0.045), Size = Vector3.new(0.178, 0.151, 0.297), Triangles = 92 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.380, -1.205),
				Aim = Vector3.new(0.000, 0.535, 0.590),
				LeftHand = Vector3.new(-0.070, -0.040, 0.020),
				Underbarrel = Vector3.new(0.000, 0.210, -0.950),
				MuzzleMount = Vector3.new(0.000, 0.380, -1.200),
				MagWell = Vector3.new(0.000, 0.230, -0.070),
			},
		},
		M1911 = {
			Length = 1.490,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.022, -0.523), Size = Vector3.new(0.124, 0.635, 1.415), Triangles = 420 },
				{ Name = "Wood", Role = "Wood", Center = Vector3.new(0.000, -0.042, 0.005), Size = Vector3.new(0.166, 0.450, 0.269), Triangles = 3058 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.123, -0.530), Size = Vector3.new(0.174, 0.652, 1.490), Triangles = 952 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, -0.090, 0.018), Size = Vector3.new(0.124, 0.668, 0.291), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(0.000, 0.395, -0.575), Size = Vector3.new(0.130, 0.210, 1.390), Triangles = 716 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.276, 0.053), Size = Vector3.new(0.142, 0.093, 0.263), Triangles = 44 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.370, -1.275),
				Aim = Vector3.new(0.000, 0.510, 0.610),
				LeftHand = Vector3.new(-0.060, -0.040, 0.020),
				MuzzleMount = Vector3.new(0.000, 0.370, -1.270),
				MagWell = Vector3.new(0.000, 0.230, -0.050),
			},
		},
		DEAGLE = {
			Length = 1.851,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.030, -0.685), Size = Vector3.new(0.164, 0.702, 1.831), Triangles = 648 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, -0.074, 0.008), Size = Vector3.new(0.186, 0.568, 0.433), Triangles = 492 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.009, 0.347, -0.706), Size = Vector3.new(0.177, 0.506, 1.828), Triangles = 1454 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, -0.115, 0.023), Size = Vector3.new(0.134, 0.725, 0.404), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(0.000, 0.442, -0.220), Size = Vector3.new(0.215, 0.305, 0.720), Triangles = 640 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.200, 0.051), Size = Vector3.new(0.202, 0.156, 0.317), Triangles = 60 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.420, -1.625),
				Aim = Vector3.new(0.000, 0.600, 0.630),
				LeftHand = Vector3.new(-0.070, -0.050, 0.030),
				Optic = Vector3.new(0.000, 0.595, -1.050),
				MagWell = Vector3.new(0.000, 0.220, -0.080),
			},
		},
		G18 = {
			Length = 1.556,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.016, -0.486), Size = Vector3.new(0.170, 0.660, 1.387), Triangles = 1357 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.003, 0.297, -0.690), Size = Vector3.new(0.173, 0.366, 0.990), Triangles = 516 },
				{ Name = "Mag", Role = "Primary", Center = Vector3.new(0.000, -0.341, 0.091), Size = Vector3.new(0.144, 1.195, 0.530), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(-0.007, 0.415, -0.550), Size = Vector3.new(0.173, 0.250, 1.300), Triangles = 794 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.194, 0.045), Size = Vector3.new(0.178, 0.151, 0.297), Triangles = 92 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.380, -1.205),
				Aim = Vector3.new(0.000, 0.535, 0.590),
				LeftHand = Vector3.new(-0.070, -0.040, 0.020),
				Underbarrel = Vector3.new(0.000, 0.210, -0.950),
				MuzzleMount = Vector3.new(0.000, 0.380, -1.200),
				MagWell = Vector3.new(0.000, 0.230, -0.070),
			},
		},
	},
	Attachments = {
		ATT_RedDot = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(-0.005, 0.140, 0.000), Size = Vector3.new(0.210, 0.320, 0.260), Triangles = 1200 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.200, -0.097), Size = Vector3.new(0.099, 0.099, 0.005), Triangles = 96 },
				{ Name = "Reticle", Role = "Reticle", Center = Vector3.new(0.000, 0.200, -0.093), Size = Vector3.new(0.011, 0.011, 0.002), Triangles = 32 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.200, 0.550),
			},
		},
		ATT_Holo = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.015, 0.125, 0.030), Size = Vector3.new(0.210, 0.290, 0.380), Triangles = 640 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.180, -0.055), Size = Vector3.new(0.140, 0.150, 0.176), Triangles = 24 },
				{ Name = "Reticle", Role = "Reticle", Center = Vector3.new(0.000, 0.170, -0.132), Size = Vector3.new(0.063, 0.063, 0.003), Triangles = 224 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.170, 0.550),
			},
		},
		ATT_Scope4x = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(-0.002, 0.130, 0.000), Size = Vector3.new(0.225, 0.300, 0.720), Triangles = 1168 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.190, 0.008), Size = Vector3.new(0.115, 0.115, 0.725), Triangles = 176 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.190, 0.610),
			},
		},
		ATT_ScopeLong = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.015, 0.190, 0.020), Size = Vector3.new(0.250, 0.420, 1.520), Triangles = 3324 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.240, 0.022), Size = Vector3.new(0.159, 0.159, 1.527), Triangles = 192 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.240, 1.180),
			},
		},
		ATT_Suppressor = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.000, -0.425), Size = Vector3.new(0.139, 0.139, 0.850), Triangles = 1240 },
			},
			Points = {
				MuzzleOffset = Vector3.new(0.000, 0.000, -0.850),
			},
		},
		ATT_Compensator = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.000, -0.100), Size = Vector3.new(0.091, 0.091, 0.200), Triangles = 536 },
			},
			Points = {
				MuzzleOffset = Vector3.new(0.000, 0.000, -0.200),
			},
		},
		ATT_VerticalGrip = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.295, 0.000), Size = Vector3.new(0.150, 0.630, 0.240), Triangles = 956 },
			},
			Points = {
			},
		},
		ATT_AngledGrip = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.110, 0.022), Size = Vector3.new(0.150, 0.260, 0.476), Triangles = 562 },
			},
			Points = {
			},
		},
		ATT_Laser = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.082, 0.004, 0.000), Size = Vector3.new(0.165, 0.168, 0.340), Triangles = 404 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.100, 0.000, -0.162), Size = Vector3.new(0.057, 0.118, 0.007), Triangles = 112 },
			},
			Points = {
				Beam = Vector3.new(0.100, 0.035, -0.170),
			},
		},
	},
}
