-- Generated by tools/blender/build_guns.py. Do not edit by hand.
-- All vectors are in game space (studs): +X right, +Y up, -Z forward (barrel), origin = pistol-grip centre.
return {
	Guns = {
		M4 = {
			Length = 4.440,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.022, 0.370, -1.070), Size = Vector3.new(0.306, 0.620, 2.820), Triangles = 4434 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.182, 0.620), Size = Vector3.new(0.180, 0.976, 1.619), Triangles = 1158 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.020, 0.522, -0.905), Size = Vector3.new(0.302, 0.715, 4.210), Triangles = 2222 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.062, -0.758), Size = Vector3.new(0.158, 1.004, 0.485), Triangles = 544 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.490, -1.330), Size = Vector3.new(0.264, 0.284, 0.120), Triangles = 92 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.500, -3.010),
				Aim = Vector3.new(0.000, 0.830, 0.730),
				LeftHand = Vector3.new(0.000, 0.355, -1.750),
				Optic = Vector3.new(0.000, 0.680, -0.350),
				Underbarrel = Vector3.new(0.000, 0.355, -1.800),
				MuzzleMount = Vector3.new(0.000, 0.500, -2.880),
				Side = Vector3.new(0.125, 0.490, -2.000),
				MagWell = Vector3.new(0.000, 0.440, -0.695),
			},
		},
		MP5 = {
			Length = 4.180,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.405, -0.245), Size = Vector3.new(0.200, 0.450, 1.590), Triangles = 526 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.162, -0.030), Size = Vector3.new(0.268, 0.948, 3.260), Triangles = 2004 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.063, 0.461, -0.992), Size = Vector3.new(0.336, 0.675, 3.175), Triangles = 2592 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, -0.121, -0.761), Size = Vector3.new(0.120, 0.902, 0.442), Triangles = 460 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.411, -1.550), Size = Vector3.new(0.278, 0.159, 0.100), Triangles = 124 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.470, -2.580),
				Aim = Vector3.new(0.000, 0.750, 0.910),
				LeftHand = Vector3.new(0.000, 0.335, -1.330),
				Optic = Vector3.new(0.000, 0.685, -0.150),
				MagWell = Vector3.new(0.000, 0.330, -0.650),
			},
		},
		SR25 = {
			Length = 5.340,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.022, 0.370, -1.355), Size = Vector3.new(0.316, 0.620, 3.390), Triangles = 5800 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.241, 0.730), Size = Vector3.new(0.180, 1.095, 1.839), Triangles = 1278 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.020, 0.425, -1.120), Size = Vector3.new(0.312, 0.910, 5.139), Triangles = 2564 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, 0.122, -0.748), Size = Vector3.new(0.164, 0.663, 0.474), Triangles = 308 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.490, -1.460), Size = Vector3.new(0.274, 0.294, 0.120), Triangles = 92 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.500, -3.700),
				Aim = Vector3.new(0.000, 0.830, 0.730),
				LeftHand = Vector3.new(0.000, 0.350, -1.900),
				Optic = Vector3.new(0.000, 0.680, -0.400),
				Underbarrel = Vector3.new(0.000, 0.350, -2.200),
				MuzzleMount = Vector3.new(0.000, 0.500, -3.500),
				Side = Vector3.new(0.130, 0.490, -2.400),
				MagWell = Vector3.new(0.000, 0.440, -0.720),
			},
		},
		VSR = {
			Length = 5.870,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.106, -0.285), Size = Vector3.new(0.160, 0.787, 4.070), Triangles = 1190 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.160, 1.777), Size = Vector3.new(0.170, 0.680, 0.065), Triangles = 108 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.221, -1.288), Size = Vector3.new(0.174, 0.789, 5.544), Triangles = 2940 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, 0.264, -0.600), Size = Vector3.new(0.120, 0.193, 0.280), Triangles = 88 },
				{ Name = "Bolt", Role = "Metal", Center = Vector3.new(0.117, 0.424, 0.060), Size = Vector3.new(0.362, 0.251, 1.040), Triangles = 424 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.310, -1.680), Size = Vector3.new(0.168, 0.240, 0.120), Triangles = 156 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.480, -4.070),
				Aim = Vector3.new(0.000, 0.680, 0.910),
				LeftHand = Vector3.new(0.000, 0.230, -1.550),
				Optic = Vector3.new(0.000, 0.615, -0.250),
				Underbarrel = Vector3.new(0.000, 0.255, -2.000),
				MagWell = Vector3.new(0.000, 0.360, -0.600),
			},
		},
		M870 = {
			Length = 5.040,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.078, -0.740), Size = Vector3.new(0.210, 0.705, 1.180), Triangles = 1222 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, -0.075, 1.497), Size = Vector3.new(0.170, 0.730, 0.085), Triangles = 108 },
				{ Name = "Wood", Role = "Wood", Center = Vector3.new(0.000, -0.052, 0.650), Size = Vector3.new(0.160, 0.756, 1.620), Triangles = 316 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.055, -1.860), Size = Vector3.new(0.200, 0.560, 3.279), Triangles = 940 },
				{ Name = "Pump", Role = "Wood", Center = Vector3.new(0.000, 0.145, -1.880), Size = Vector3.new(0.184, 0.232, 0.900), Triangles = 1720 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.145, -1.398), Size = Vector3.new(0.188, 0.236, 0.055), Triangles = 80 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.250, -3.500),
				Aim = Vector3.new(0.000, 0.470, 0.450),
				LeftHand = Vector3.new(0.000, 0.035, -1.880),
				Optic = Vector3.new(0.000, 0.430, -0.750),
				MagWell = Vector3.new(0.000, -0.060, -1.020),
			},
		},
		AK74 = {
			Length = 5.000,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.477, -0.251), Size = Vector3.new(0.200, 0.355, 1.538), Triangles = 304 },
				{ Name = "Wood", Role = "Wood", Center = Vector3.new(0.000, 0.215, -0.120), Size = Vector3.new(0.200, 0.992, 3.480), Triangles = 1424 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.065, 0.320, -0.820), Size = Vector3.new(0.370, 0.800, 5.000), Triangles = 2126 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.187, -0.766), Size = Vector3.new(0.126, 1.034, 0.578), Triangles = 548 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.418, -1.620), Size = Vector3.new(0.212, 0.255, 0.120), Triangles = 156 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.480, -3.330),
				Aim = Vector3.new(0.000, 0.720, -0.600),
				LeftHand = Vector3.new(0.000, 0.310, -1.500),
				Optic = Vector3.new(0.000, 0.690, -0.200),
				MuzzleMount = Vector3.new(0.000, 0.480, -3.020),
				MagWell = Vector3.new(0.000, 0.330, -0.640),
			},
		},
		VECTOR = {
			Length = 3.060,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.310, -0.485), Size = Vector3.new(0.240, 0.740, 2.010), Triangles = 2478 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.171, 0.644), Size = Vector3.new(0.180, 0.959, 1.612), Triangles = 934 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.030, 0.492, -0.280), Size = Vector3.new(0.260, 0.656, 2.660), Triangles = 1208 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.175, -0.630), Size = Vector3.new(0.134, 0.890, 0.224), Triangles = 176 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.100, -0.950), Size = Vector3.new(0.252, 0.200, 0.120), Triangles = 44 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.360, -1.610),
				Aim = Vector3.new(0.000, 0.800, 0.850),
				LeftHand = Vector3.new(0.000, 0.050, -0.920),
				Optic = Vector3.new(0.000, 0.680, -0.300),
				Underbarrel = Vector3.new(0.000, 0.205, -1.340),
				MuzzleMount = Vector3.new(0.000, 0.360, -1.520),
				Side = Vector3.new(0.125, 0.360, -1.340),
				MagWell = Vector3.new(0.000, 0.270, -0.630),
			},
		},
		MP7 = {
			Length = 2.520,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.170, -0.319), Size = Vector3.new(0.270, 0.999, 1.518), Triangles = 2930 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.190, 0.185), Size = Vector3.new(0.180, 0.820, 2.030), Triangles = 436 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.457, -0.100), Size = Vector3.new(0.230, 0.626, 2.440), Triangles = 792 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, -0.117, 0.056), Size = Vector3.new(0.114, 0.745, 0.332), Triangles = 176 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.050, -0.745), Size = Vector3.new(0.112, 0.080, 0.200), Triangles = 44 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.420, -1.320),
				Aim = Vector3.new(0.000, 0.780, 0.860),
				LeftHand = Vector3.new(0.000, 0.000, -0.745),
				Optic = Vector3.new(0.000, 0.670, -0.250),
				MuzzleMount = Vector3.new(0.000, 0.420, -1.140),
				Side = Vector3.new(0.135, 0.420, -0.750),
				MagWell = Vector3.new(0.000, 0.240, -0.045),
			},
		},
		P90 = {
			Length = 2.640,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.357, -0.047), Size = Vector3.new(0.320, 1.215, 2.453), Triangles = 2238 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.230, 0.800), Size = Vector3.new(0.248, 0.280, 0.480), Triangles = 124 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.165, -0.825), Size = Vector3.new(0.340, 0.789, 1.270), Triangles = 532 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(0.000, 0.765, 0.180), Size = Vector3.new(0.240, 0.130, 1.560), Triangles = 108 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.060, -0.660), Size = Vector3.new(0.272, 0.120, 0.120), Triangles = 44 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.520, -1.460),
				Aim = Vector3.new(0.000, 1.030, 0.350),
				LeftHand = Vector3.new(0.000, -0.120, -0.660),
				Optic = Vector3.new(0.000, 0.965, -0.550),
				MuzzleMount = Vector3.new(0.000, 0.520, -1.320),
				Side = Vector3.new(0.165, 0.520, -0.900),
				MagWell = Vector3.new(0.000, 0.830, 0.180),
			},
		},
		M249 = {
			Length = 5.400,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.045, 0.465, -0.685), Size = Vector3.new(0.350, 0.780, 2.330), Triangles = 1652 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.177, 0.000), Size = Vector3.new(0.240, 0.966, 3.800), Triangles = 1626 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.233, -1.477), Size = Vector3.new(0.530, 1.391, 4.045), Triangles = 2154 },
				{ Name = "Mag", Role = "Secondary", Center = Vector3.new(-0.090, 0.116, -0.520), Size = Vector3.new(0.319, 0.933, 0.640), Triangles = 824 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, 0.415, -1.610), Size = Vector3.new(0.252, 0.230, 0.120), Triangles = 156 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.550, -3.510),
				Aim = Vector3.new(0.000, 0.900, 0.620),
				LeftHand = Vector3.new(0.000, 0.310, -1.500),
				Optic = Vector3.new(0.000, 0.855, -0.450),
				Underbarrel = Vector3.new(0.000, 0.310, -1.550),
				MuzzleMount = Vector3.new(0.000, 0.550, -3.330),
				Side = Vector3.new(0.150, 0.450, -1.520),
				MagWell = Vector3.new(-0.080, 0.300, -0.520),
			},
		},
		G17 = {
			Length = 1.300,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.012, -0.210), Size = Vector3.new(0.170, 0.645, 1.260), Triangles = 1469 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.003, 0.297, -0.428), Size = Vector3.new(0.173, 0.366, 0.835), Triangles = 516 },
				{ Name = "Mag", Role = "Primary", Center = Vector3.new(0.000, -0.075, 0.013), Size = Vector3.new(0.144, 0.659, 0.369), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(0.000, 0.415, -0.210), Size = Vector3.new(0.160, 0.250, 1.300), Triangles = 630 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.120, 0.025), Size = Vector3.new(0.176, 0.120, 0.315), Triangles = 124 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.380, -0.865),
				Aim = Vector3.new(0.000, 0.535, 0.930),
				LeftHand = Vector3.new(-0.070, -0.040, 0.020),
				Underbarrel = Vector3.new(0.000, 0.210, -0.650),
				MuzzleMount = Vector3.new(0.000, 0.380, -0.860),
				MagWell = Vector3.new(0.000, 0.230, -0.070),
			},
		},
		M1911 = {
			Length = 1.515,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.017, -0.265), Size = Vector3.new(0.124, 0.623, 1.330), Triangles = 420 },
				{ Name = "Wood", Role = "Wood", Center = Vector3.new(0.000, -0.040, 0.008), Size = Vector3.new(0.162, 0.460, 0.315), Triangles = 3330 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(0.000, 0.070, -0.218), Size = Vector3.new(0.170, 0.758, 1.515), Triangles = 944 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, -0.080, 0.017), Size = Vector3.new(0.124, 0.647, 0.280), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(0.000, 0.395, -0.275), Size = Vector3.new(0.130, 0.210, 1.390), Triangles = 716 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.240, 0.075), Size = Vector3.new(0.142, 0.116, 0.218), Triangles = 44 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.370, -0.975),
				Aim = Vector3.new(0.000, 0.510, 0.910),
				LeftHand = Vector3.new(-0.060, -0.040, 0.020),
				MuzzleMount = Vector3.new(0.000, 0.370, -0.970),
				MagWell = Vector3.new(0.000, 0.230, -0.050),
			},
		},
		DEAGLE = {
			Length = 1.837,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.027, -0.440), Size = Vector3.new(0.164, 0.677, 1.720), Triangles = 656 },
				{ Name = "Furniture", Role = "Secondary", Center = Vector3.new(0.000, 0.001, 0.030), Size = Vector3.new(0.400, 0.621, 0.700), Triangles = 1411 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.009, 0.347, -0.401), Size = Vector3.new(0.177, 0.506, 1.837), Triangles = 1494 },
				{ Name = "Mag", Role = "Metal", Center = Vector3.new(0.000, -0.096, 0.029), Size = Vector3.new(0.134, 0.681, 0.376), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(0.000, 0.442, 0.130), Size = Vector3.new(0.215, 0.305, 0.660), Triangles = 644 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.150, 0.047), Size = Vector3.new(0.200, 0.110, 0.300), Triangles = 60 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.420, -1.325),
				Aim = Vector3.new(0.000, 0.600, 0.950),
				LeftHand = Vector3.new(-0.070, -0.050, 0.030),
				Optic = Vector3.new(0.000, 0.595, -0.750),
				MagWell = Vector3.new(0.000, 0.220, -0.070),
			},
		},
		G18 = {
			Length = 1.300,
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.012, -0.210), Size = Vector3.new(0.170, 0.645, 1.260), Triangles = 1469 },
				{ Name = "Metal", Role = "Metal", Center = Vector3.new(-0.003, 0.297, -0.428), Size = Vector3.new(0.173, 0.366, 0.835), Triangles = 516 },
				{ Name = "Mag", Role = "Primary", Center = Vector3.new(0.000, -0.340, 0.086), Size = Vector3.new(0.144, 1.189, 0.516), Triangles = 176 },
				{ Name = "Slide", Role = "Metal", Center = Vector3.new(-0.007, 0.415, -0.210), Size = Vector3.new(0.173, 0.250, 1.300), Triangles = 794 },
				{ Name = "Tape", Role = "Accent", Center = Vector3.new(0.000, -0.120, 0.025), Size = Vector3.new(0.176, 0.120, 0.315), Triangles = 124 },
			},
			Points = {
				Muzzle = Vector3.new(0.000, 0.380, -0.865),
				Aim = Vector3.new(0.000, 0.535, 0.930),
				LeftHand = Vector3.new(-0.070, -0.040, 0.020),
				Underbarrel = Vector3.new(0.000, 0.210, -0.650),
				MuzzleMount = Vector3.new(0.000, 0.380, -0.860),
				MagWell = Vector3.new(0.000, 0.230, -0.070),
			},
		},
	},
	Attachments = {
		ATT_RedDot = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(-0.005, 0.140, 0.000), Size = Vector3.new(0.210, 0.320, 0.260), Triangles = 1200 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.200, -0.097), Size = Vector3.new(0.099, 0.099, 0.005), Triangles = 96 },
				{ Name = "Reticle", Role = "Reticle", Center = Vector3.new(0.000, 0.200, -0.093), Size = Vector3.new(0.011, 0.011, 0.002), Triangles = 32 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.200, 0.550),
			},
		},
		ATT_Holo = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.015, 0.125, 0.030), Size = Vector3.new(0.210, 0.290, 0.380), Triangles = 640 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.180, -0.055), Size = Vector3.new(0.140, 0.150, 0.176), Triangles = 24 },
				{ Name = "Reticle", Role = "Reticle", Center = Vector3.new(0.000, 0.170, -0.132), Size = Vector3.new(0.063, 0.063, 0.003), Triangles = 224 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.170, 0.550),
			},
		},
		ATT_Scope4x = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(-0.002, 0.130, 0.000), Size = Vector3.new(0.225, 0.300, 0.720), Triangles = 1168 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.190, 0.008), Size = Vector3.new(0.115, 0.115, 0.725), Triangles = 176 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.190, 0.610),
			},
		},
		ATT_ScopeLong = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.015, 0.190, 0.020), Size = Vector3.new(0.250, 0.420, 1.520), Triangles = 3324 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.000, 0.240, 0.022), Size = Vector3.new(0.159, 0.159, 1.527), Triangles = 192 },
			},
			Points = {
				Aim = Vector3.new(0.000, 0.240, 1.180),
			},
		},
		ATT_Suppressor = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.000, -0.425), Size = Vector3.new(0.139, 0.139, 0.850), Triangles = 1240 },
			},
			Points = {
				MuzzleOffset = Vector3.new(0.000, 0.000, -0.850),
			},
		},
		ATT_Compensator = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, 0.000, -0.100), Size = Vector3.new(0.091, 0.091, 0.200), Triangles = 536 },
			},
			Points = {
				MuzzleOffset = Vector3.new(0.000, 0.000, -0.200),
			},
		},
		ATT_VerticalGrip = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.295, 0.000), Size = Vector3.new(0.150, 0.630, 0.240), Triangles = 956 },
			},
			Points = {
			},
		},
		ATT_AngledGrip = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.000, -0.110, 0.022), Size = Vector3.new(0.150, 0.260, 0.476), Triangles = 562 },
			},
			Points = {
			},
		},
		ATT_Laser = {
			Pieces = {
				{ Name = "Body", Role = "Primary", Center = Vector3.new(0.082, 0.004, 0.000), Size = Vector3.new(0.165, 0.168, 0.340), Triangles = 404 },
				{ Name = "Glass", Role = "Glass", Center = Vector3.new(0.100, 0.000, -0.162), Size = Vector3.new(0.057, 0.118, 0.007), Triangles = 112 },
			},
			Points = {
				Beam = Vector3.new(0.100, 0.035, -0.170),
			},
		},
	},
}
